apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-shiparc-deployment
  labels:
    app: docker-k8s-shiparc
spec:
  replica: 1
  selector:
    matchLabels:
      app: docker-k8s-shiparc
  template:
    metadata:
      labels:
        app: docker-k8s-shiparc
    spec:
      containers:
        - name: docker-k8s-shiparc
          image: raghugore/shiparc
          ports:
            - containerPort: 3000
